fail_on_violations: false

rubocop:
  enabled: true
  config_file: .rubocop.yml

scss:
  enabled: true
  config_file: .scss-lint.yml

eslint:
  enabled: true
  config_file: .eslintrc.

coffeescript:
  enabled: false
